### ISSUE TITLE
Footer is not fixed to bottom

### ISSUE THREAD

**Issue by nidhinkumar06** [reduction-admin/react-reduction#32]
When the page is empty the footer gets jumped to top i would like to keep the footer at the bottom. Is there any to do it

![React App (2)](https://user-images.githubusercontent.com/10459220/60153071-b1af7a00-9800-11e9-8b32-75589c362968.jpg)

**Comment by simsim0709** [comment]
You want to set min-height for `cr-page` css class.
Like below:

```scss
// src/styles/components/_page.scss

.cr-page {
  min-height: calc(100vh - 73px - 40px); // 73px - header height, 40px - footer height
...
}
```
